project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with Quarto"
  page-navigation: true
  
  navbar:
    title: Estéfano Souza
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - sidebar:es-profile
      - text: "Posts"
        href: posts/index.qmd
  
  sidebar:
    - id: es-profile
      title: "Perfil"
      style: docked
      collapse-level: 2
      contents: 
        - profile/academics.qmd
        - profile/experience.qmd
        - profile/certifications.qmd
        # - profile/publications.qmd
  # tools:  
  #   - icon: github
  #     href: github.com
      
format:
  html:
    # mainfont: "sans-serif"
    # backgroundcolor: "lightskyblue"
    # fontcolor: "darkblue"
    # linkcolor: "black"
    theme: [sandstone, styles.scss]
    css: styles.css

